### PR TITLE
 Fixes Resolv for Linux

### PR DESCRIPTION
**Pull request by cjgratacos**
### Description
On newer version of linux, the resolv.conf file contains non informative comments line at the top of the file, which brakes the resolvr functionality inside of pygmy. This lines should be removed for making the resolvr.rb work on newer version of linux.

### Picture
**File**: `resolvr.conf` on Ubuntu 17.10 and various flavors of Ubuntu 17.10
screenshot from 2017-11-13 21-51-10

### CODE REVIEW

**Comment by dasrecht** [comment]
Hi @cjgratacos - Thanks for the PR! We'll have a look at this and if testing goes well we'll merge it.

**Comment by cjgratacos** [comment]
@dasrecht thanks for the quick response.

**Comment by naume** [comment]
:+1: Nice got this error too on ubuntu 17.10 here

**Comment by dasrecht** [comment]
@naume Ubuntu 17.10 seems also to yield other issues. I'm working on a Documentation update for that also as the old documentation does not work with the current state of the ubuntu system anymore. (but that's related to the local dns resolver)

**Comment by fubarhouse** [comment]
@dasrecht,

Could you provide an ETA on the updated documentation, or could you provide a link?

**Comment by Schnitzel** [comment]
we released 0.9.9 which has now a new flag: `--no-resolver` for `pygmy up` which allows to disable the nameserver system within pygmy that creates all the linux issues.

Additionally our nameservers are now replying with `*.docker.amazee.io` and resolve also to `127.0.0.1` (proof: https://www.digwebinterface.com/?hostnames=foobar.docker.amazee.io&type=&ns=resolver&useresolver=8.8.4.4&nameservers=)

So unless your nameserver is not blocking `127.0.0.1` we don't need the nameserver system anymore

**Comment by fubarhouse** [comment]
Sweet, thanks.

Not using this myself but I know some who're interested!

**Comment by dasrecht** [comment]
Closing the PR as the version 0.9.9 has a similar feature that solves the issue.

**Pull request closed without merging**
